// Conflux Home — Radar Onboarding (Intelligence Briefing)
// Radar introduces itself through 4 briefing panels.
// No data required — pure explainer.
//
// LocalStorage: 'radar-onboarding-completed' (permanent — one time only)
//
// Design: dark glass cockpit, SVG radar illustration,
//         color-coded ripple categories, tactical card reveal,
//         briefing aesthetic — feels like reading a classified dossier

import { useState, useEffect, useCallback } from 'react';
import '../styles/radar-boot.css';

const ONBOARDING_DONE_KEY = 'radar-onboarding-completed';

const BRIEFINGS = [
  {
    id: 'ripples',
    accentColor: '#06b6d4',
    label: '01 // RIPPLES',
    title: 'Your life sends out ripples.',
    body: "Every decision, transaction, dream, and habit creates a ripple in your data. Ripple Radar listens across all of Conflux — Budget, Kitchen, Dreams, Life — and detects patterns before they surface.",
    hint: 'Ripples have a confidence score: how certain the system is that this signal matters.',
    visual: 'radar',
  },
  {
    id: 'categories',
    accentColor: '#10b981',
    label: '02 // CATEGORIES',
    title: 'Four dimensions of your life.',
    body: 'Each ripple is color-coded by category: green for money, amber for dreams, violet for creative energy, cyan for everything else. Watch how they cluster — a dream ripple near a finance ripple might mean something worth exploring.',
    hint: 'Tap any blip to expand it into a Signal Card.',
    visual: 'blips',
  },
  {
    id: 'briefing',
    accentColor: '#f59e0b',
    label: '03 // BRIEFING',
    title: 'Daily tactical intelligence.',
    body: "Every day, Radar generates an AI briefing — a summary of the week's signals, what patterns emerged, what to watch. Like a morning intelligence report for your life.",
    hint: 'Generated by AI — no two briefings are the same.',
    visual: 'briefing',
  },
  {
    id: 'threads',
    accentColor: '#8b5cf6',
    label: '04 // THREADS',
    title: 'Topics under observation.',
    body: "Signal Threads are long-running investigations — Radar tracks a topic over time, watches it evolve, and predicts where it's heading. Start a thread on anything: 'my spending habits', 'creative block', 'career direction'.",
    hint: 'Predictions update as new data comes in.',
    visual: 'thread',
  },
];

interface Props {
  onComplete: () => void;
}

export function hasCompletedRadarOnboarding(): boolean {
  return localStorage.getItem(ONBOARDING_DONE_KEY) === 'true';
}

export default function RadarOnboarding({ onComplete }: Props) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [entered, setEntered] = useState(false);
  const [cardVisible, setCardVisible] = useState(false);
  const [showHint, setShowHint] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setEntered(true), 100);
    const t2 = setTimeout(() => setCardVisible(true), 350);
    const t3 = setTimeout(() => setShowHint(true), 1200);
    return () => { clearTimeout(t); clearTimeout(t2); clearTimeout(t3); };
  }, []);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'ArrowRight' || e.key === 'ArrowDown') { e.preventDefault(); handleNext(); }
      if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') { e.preventDefault(); handlePrev(); }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [currentIndex]);

  const handleNext = useCallback(() => {
    if (currentIndex < BRIEFINGS.length - 1) {
      setCardVisible(false);
      setShowHint(false);
      setTimeout(() => {
        setCurrentIndex(c => c + 1);
        setCardVisible(true);
        setTimeout(() => setShowHint(true), 1000);
      }, 220);
    } else {
      localStorage.setItem(ONBOARDING_DONE_KEY, 'true');
      onComplete();
    }
  }, [currentIndex, onComplete]);

  const handlePrev = useCallback(() => {
    if (currentIndex > 0) {
      setCardVisible(false);
      setShowHint(false);
      setTimeout(() => {
        setCurrentIndex(c => c - 1);
        setCardVisible(true);
        setTimeout(() => setShowHint(true), 800);
      }, 220);
    }
  }, [currentIndex]);

  const current = BRIEFINGS[currentIndex];
  const isLast = currentIndex === BRIEFINGS.length - 1;
  const progress = ((currentIndex + 1) / BRIEFINGS.length) * 100;

  return (
    <div className={`radar-onboard-root ${entered ? 'entered' : ''}`}>

      {/* Header */}
      <div className="radar-onboard-header">
        <div className="radar-onboard-eyebrow">RIPPLE RADAR</div>
        <div className="radar-onboard-header-label">INTELLIGENCE BRIEFING</div>
      </div>

      {/* Briefing card */}
      <div
        className={`radar-onboard-card ${cardVisible ? 'visible' : ''}`}
        style={{ '--accent': current.accentColor } as React.CSSProperties}
      >
        {/* Category badge */}
        <div className="radar-onboard-category" style={{ color: current.accentColor }}>
          <div className="radar-onboard-cat-dot" style={{ background: current.accentColor }} />
          {current.label}
        </div>

        {/* Radar SVG illustration */}
        <div className="radar-onboard-visual">
          {current.visual === 'radar' && (
            <svg viewBox="0 0 160 160" className="radar-onboard-svg">
              <circle cx="80" cy="80" r="70" fill="none" stroke="rgba(6,182,212,0.1)" strokeWidth="1" />
              <circle cx="80" cy="80" r="70" fill="none" stroke={current.accentColor} strokeWidth="1" strokeDasharray="5 3" opacity="0.3" />
              <circle cx="80" cy="80" r="45" fill="none" stroke="rgba(6,182,212,0.08)" strokeWidth="1" />
              <circle cx="80" cy="80" r="20" fill="none" stroke="rgba(6,182,212,0.08)" strokeWidth="1" />
              <line x1="80" y1="10" x2="80" y2="150" stroke="rgba(6,182,212,0.06)" strokeWidth="0.5" />
              <line x1="10" y1="80" x2="150" y2="80" stroke="rgba(6,182,212,0.06)" strokeWidth="0.5" />
              <circle cx="80" cy="80" r="3" fill="#06b6d4" />
              {/* Animated sweep */}
              <line
                x1="80" y1="80"
                x2="80" y2="12"
                stroke="rgba(6,182,212,0.4)"
                strokeWidth="1.5"
                className="radar-onboard-sweep"
              />
              <polygon
                points="80,80 80,12 86,80"
                fill="rgba(6,182,212,0.15)"
                className="radar-onboard-sweep"
              />
              {/* Ripple dots */}
              <circle cx="80" cy="80" r="3" fill={current.accentColor} opacity="0.8" />
              <circle cx="55" cy="55" r="4" fill={current.accentColor} opacity="0.6" className="blip-pulse" />
              <circle cx="110" cy="60" r="3" fill={current.accentColor} opacity="0.7" className="blip-pulse" style={{ animationDelay: '0.4s' }} />
              <circle cx="105" cy="95" r="3.5" fill={current.accentColor} opacity="0.5" className="blip-pulse" style={{ animationDelay: '0.8s' }} />
            </svg>
          )}

          {current.visual === 'blips' && (
            <div className="radar-onboard-category-grid">
              {[
                { color: '#10b981', label: 'Finance', icon: '💰' },
                { color: '#f59e0b', label: 'Dreams', icon: '✨' },
                { color: '#8b5cf6', label: 'Creative', icon: '🎨' },
                { color: '#06b6d4', label: 'General', icon: '📡' },
              ].map(cat => (
                <div key={cat.label} className="radar-onboard-cat-chip" style={{ borderColor: cat.color, color: cat.color }}>
                  <span>{cat.icon}</span>
                  <span>{cat.label}</span>
                </div>
              ))}
            </div>
          )}

          {current.visual === 'briefing' && (
            <div className="radar-onboard-briefing-visual">
              <div className="radar-onboard-brief-header">
                <div className="radar-onboard-brief-icon">📡</div>
                <div>
                  <div className="radar-onboard-brief-title">DAILY BRIEFING</div>
                  <div className="radar-onboard-brief-date">TODAY</div>
                </div>
              </div>
              <div className="radar-onboard-brief-lines">
                {[80, 65, 90, 55, 75].map((w, i) => (
                  <div key={i} className="radar-onboard-brief-line" style={{ width: `${w}%`, animationDelay: `${i * 0.15}s` }} />
                ))}
              </div>
              <div className="radar-onboard-brief-sentiment">
                <span style={{ color: '#10b981' }}>↑ 3 RISING</span>
                <span style={{ color: '#f59e0b' }}>· 2 SHIFTING</span>
              </div>
            </div>
          )}

          {current.visual === 'thread' && (
            <div className="radar-onboard-thread-visual">
              <div className="radar-onboard-thread-node">
                <div className="radar-onboard-thread-dot" style={{ background: '#8b5cf6' }} />
                <div className="radar-onboard-thread-line" />
                <div className="radar-onboard-thread-dot" style={{ background: '#10b981', opacity: 0.7 }} />
                <div className="radar-onboard-thread-line" />
                <div className="radar-onboard-thread-dot" style={{ background: '#06b6d4', opacity: 0.5 }} />
              </div>
              <div className="radar-onboard-thread-label">THREAD EVOLUTION →</div>
              <div className="radar-onboard-thread-prediction">
                <span>PREDICTION: </span>
                <span style={{ color: '#10b981' }}>73% CONFIDENCE</span>
              </div>
            </div>
          )}
        </div>

        {/* Title */}
        <h2 className="radar-onboard-title">{current.title}</h2>

        {/* Body */}
        <p className="radar-onboard-body">{current.body}</p>

        {/* Hint */}
        <div
          className={`radar-onboard-hint ${showHint ? 'visible' : ''}`}
          style={{ borderColor: current.accentColor, color: current.accentColor }}
        >
          💡 {current.hint}
        </div>

        {/* Progress dots */}
        <div className="radar-onboard-dots">
          {BRIEFINGS.map((_, i) => (
            <div
              key={i}
              className={`radar-onboard-dot ${i === currentIndex ? 'active' : i < currentIndex ? 'done' : ''}`}
              onClick={() => {
                if (i !== currentIndex) {
                  setCardVisible(false);
                  setShowHint(false);
                  setTimeout(() => { setCurrentIndex(i); setCardVisible(true); setTimeout(() => setShowHint(true), 800); }, 220);
                }
              }}
            />
          ))}
        </div>
      </div>

      {/* Controls */}
      <div className="radar-onboard-controls">
        <button
          className="radar-onboard-btn radar-onboard-back"
          onClick={currentIndex === 0 ? undefined : handlePrev}
          disabled={currentIndex === 0}
        >
          ← BACK
        </button>

        <div className="radar-onboard-progress-track">
          <div className="radar-onboard-progress-fill" style={{ width: `${progress}%` }} />
        </div>

        <button className="radar-onboard-btn radar-onboard-next" onClick={handleNext}>
          {isLast ? '📡 ACTIVATE RADAR' : 'NEXT →'}
        </button>
      </div>

      <div className="radar-onboard-hint-line">← → to navigate · Enter to continue</div>
    </div>
  );
}
